# Generated by Django 5.2 on 2025-05-07 17:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('publica', models.BooleanField(default=True)),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='colecciones/miniaturas/')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('extensiones_permitidas', models.CharField(help_text='Extensiones separadas por comas (ej: mp4,avi,mov)', max_length=200)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS para el icono (ej: fa-video)', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Archivo',
                'verbose_name_plural': 'Tipos de Archivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='multimedia/archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mp3', 'wav', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='multimedia/miniaturas/')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('tamaño_bytes', models.BigIntegerField(default=0)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('coleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='gestor_multimedia.coleccion')),
                ('tipo_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestor_multimedia.tipoarchivo')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia',
                'verbose_name_plural': 'Archivos Multimedia',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobado', models.BooleanField(default=False)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='gestor_multimedia.archivomultimedia')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
